# Generated by Django 5.0.6 on 2024-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todolist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='attachments',
            field=models.FileField(null=True, upload_to='public'),
        ),
    ]
