# Generated by Django 5.0.6 on 2024-05-19 10:44

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='private_file',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='private'),
        ),
    ]
